all:
	g++ -I/usr/local/include -I/usr/include -L/usr/local/lib AttributeParserTest.cpp ../Parsers/AttributeParser.cpp \
	../Parsers/TokenGenerator.cpp ../Types/NodeValue.cpp -std=c++0x -o run -lwt -lwthttp -lboost_signals -lhiredis -lturnleft -lcrypto -lcityhash -lwt
