all:
	g++ NodeValueParserTest.cpp ../Parsers/NodeValueParser.cpp ../Types/NodeValue.cpp ../Parsers/NodeValueParser/CommandParser.cpp ../Parsers/NodeValueParser/StateParser.cpp ../Parsers/NodeValueParser/AttributeParser.cpp ../Parsers/NodeValueParser/MathParser.cpp -std=c++0x -o runtest
