#!/usr/bin/env python
import sys
import os
from moguio import RedisWriter
from moguio import PathImporter
from moguio.Exporter.DatabaseExporter import DatabaseExporter
import pyboro

import src
args = src.cli_parser.getCLIArgs()
command = args.command[0]

if __name__ == "__main__":
    if args.v:
        pyboro.Lexer.VERBAL = (args.v==5)
    if command == "import":
        writer = RedisWriter.RedisWriter(args)
        paths = args.command[1:]

        for path in paths:
            p = PathImporter.PathImporter(path,args.v)
            lexed = p.get_results()
            converted = p.convert_results(lexed)
            writer.write(converted)

    # This will be tweaked in the future to be much more
    # advanced; for now, it will just dump everything out
    # to stdout
    if command == "export":
        exports = []
        exporter = DatabaseExporter()
        exports.extend (exporter.export_templates())
        exports.extend (exporter.export_widgets())
        exports.extend (exporter.export_validators())
        exports.extend (exporter.export_data())
        exports.extend (exporter.export_policies())
        for entry in exports:
            sys.stdout.write(entry)

    if command == "start":
        src.start.start(args)

