#!/usr/bin/env python

import moguio
import src
#import src.cli_parser
args = src.cli_parser.getCLIArgs()
command = args.command[0]

cli_map = {
    "import"            :   moguio.ScriptImporter.doImport
#    "set-root"          :   cli.set_root,
}
if __name__ == "__main__":
    cli_map[command](args)
