#!/usr/bin/env python

from redis import Redis
from src import cli

args,conf = cli.getCLIArgs()
command = args.command[0]
args.conf = conf

cli_map = {
    "import"            :   cli.mogu_import,
    "merge-sessions"    :   cli.merge_sessions,
    "export"            :   cli.export_all,
    "export-widget"     :   cli.export_widget,
    "start"             :   cli.start,
    "purge-sessions"    :   cli.purge_sessions,
    "init"              :   cli.init,
    "create_config"     :   cli.create_config,
}
if __name__ == "__main__":
    cli_map[command](args)
