enum MoguSyntax {
	__NONE__                               = 0
	,own                                    = 1
	,parent                                 = 2
	,children                               = 3
	,siblings                               = 4
	,click                                  = 5
	,mouseover                              = 6
	,style_changed                          = 7
	,keyup                                  = 8
	,fail                                   = 9
	,succeed                               = 10
	,enter_pressed                         = 11
	,hidden_changed                        = 12
	,onload                                = 13
	,clear                                 = 14
	,increment                             = 15
	,decrement                             = 16
	,test                                  = 17
	,email                                 = 18
	,reload                                = 19
	,append                                = 20
	,replace                               = 21
	,set                                   = 22
	,path                                  = 23
	,user                                  = 24
	,session                               = 25
	,reset                                 = 26
	,style                                 = 27
	,group                                 = 28
	,remove                                = 29
	,text                                  = 30
	,store                                 = 31
	,child                                 = 32
	,regex                                 = 33
	,list                                  = 34
	,string                                = 35
	,hash                                  = 36
	,data                                  = 37
	,index                                 = 38
	,slot                                  = 39
	,javascript                            = 40
	,anchor                                = 41
	,image                                 = 42
	,submit                                = 43
	,radio                                 = 44
	,textarea                              = 45
	,input                                 = 46
	,dropdown                              = 47
	,multi                                 = 48
	,container                             = 49
	,password                              = 50
	,stack                                 = 51
	,foreach                               = 52
	,name                                  = 53
	,hidden                                = 54
	,image_link                            = 55
	,to                                    = 56
	,as                                    = 57
	,at                                    = 58
	,m_widget                              = 59
	,retrieve                              = 60
	,type                                  = 61
	,mode                                  = 62
	,source                                = 63
	,location                              = 64
	,template                              = 65
	,OPER_OPPAREN				=2147483642
	,OPER_CLPAREN				=2147483643
	,OPER_PLUS				=2147483644
	,OPER_MINUS				=2147483645
	,OPER_MULT				=2147483646
	,OPER_DIV				=2147483647

}; // END MoguSyntax
