MoguSyntax = {
	"None"                           : (0,"null bit"),
	"own"                              : (1,"object"),
	"self"                             : (1,"object"),
	"parent"                           : (2,"object"),
	"children"                 : (3,"object hashkey"),
	"siblings"                         : (4,"object"),
	"clicked"                   : (5,"event trigger"),
	"click"                     : (5,"event trigger"),
	"mouseover"                 : (6,"event trigger"),
	"style changed"             : (7,"event trigger"),
	"keyup"                     : (8,"event trigger"),
	"failed test"               : (9,"event trigger"),
	"succeeded test"           : (10,"event trigger"),
	"enter pressed"            : (11,"event trigger"),
	"hidden changed"           : (12,"event trigger"),
	"loaded"                   : (13,"event trigger"),
	"clear"                           : (14,"action"),
	"increment"                       : (15,"action"),
	"incr"                            : (15,"action"),
	"decrement"                       : (16,"action"),
	"decr"                            : (16,"action"),
	"test"          : (17,"action attribute hashkey"),
	"email"                           : (18,"action"),
	"reload"                          : (19,"action"),
	"append"                          : (20,"action"),
	"replace"                         : (21,"action"),
	"set"                    : (22,"action datatype"),
	"path"                            : (23,"object"),
	"user"                            : (24,"object"),
	"session"                         : (25,"object"),
	"reset"                           : (26,"action"),
	"style"                : (27,"attribute hashkey"),
	"css"                  : (27,"attribute hashkey"),
	"group"                           : (28,"object"),
	"remove"                          : (29,"action"),
	"text"     : (30,"attribute hashkey widget type"),
	"content"  : (30,"attribute hashkey widget type"),
	"contents" : (30,"attribute hashkey widget type"),
	"store"                           : (31,"action"),
	"child"                           : (32,"object"),
	"regex"         : (33,"attribute validator type"),
	"list"                : (34,"attribute datatype"),
	"string"              : (35,"attribute datatype"),
	"hash"                   : (36,"action datatype"),
	"data"                            : (37,"object"),
	"index"                        : (38,"attribute"),
	"slot"                            : (39,"object"),
	"javascript"                      : (40,"action"),
	"link"                       : (41,"widget type"),
	"image"                      : (42,"widget type"),
	"submit"                     : (43,"widget type"),
	"radio"                      : (44,"widget type"),
	"textarea"                   : (45,"widget type"),
	"input"                      : (46,"widget type"),
	"dropdown"                   : (47,"widget type"),
	"multi"                      : (48,"widget type"),
	"container"                  : (49,"widget type"),
	"password"  : (50,"widget type attribute object"),
	"stack"                      : (51,"widget type"),
	"foreach"                    : (52,"widget type"),
	"name"                 : (53,"attribute hashkey"),
	"hidden"            : (54,"widget type attibute"),
	"image link"                 : (55,"widget type"),
	"to"                         : (56,"preposition"),
	"as"                         : (57,"preposition"),
	"at"                         : (58,"preposition"),
	"widget"                          : (59,"object"),
	"retrieve"                        : (60,"action"),
	"get"                             : (60,"action"),
	"type"                           : (61,"hashkey"),
	"mode"                           : (62,"hashkey"),
	"source"                         : (63,"hashkey"),
	"location"                       : (64,"hashkey"),
	"template"                       : (65,"hashkey"),
} # END MoguSyntax

def as_integer(string):
    global MoguSyntax
    return MoguSyntax[string.strip()][0]

# Begin mathematic operator constants
MoguOperators = {}
MoguOperators['('] = 2147483642
MoguOperators[')'] = 2147483643
MoguOperators['*'] = 2147483646
MoguOperators['+'] = 2147483644
MoguOperators['-'] = 2147483645
MoguOperators['/'] = 2147483647
