#include <Parsers/SyntaxMap.h>

enum MoguTokens{
	__NONE__,
	self,
	parent,
	children,
	siblings,
	application,
	change,
	add,
	subtract,
	multiply,
	divide,
	clear,
	increment,
	decrement,
	test,
	email,
	reload,
	append,
	replace,
	slide,
	pop,
	fade,
	emit,
	count,
	right,
	left,
	up,
	down,
	regex,
	list,
	string,
	hash,
	style,
	index,
	session,
	user,
	slot,
	javascript,
	value,
	link,
	image,
	submit,
	radio,
	textarea,
	input,
	dropdown,
	checkbox,
	multi,
	container,
	password,
	stack,
	foreach,
	index,
	name,
	hidden,
	value,
};


const static SyntaxMap <MoguTokens> syntaxMap =SyntaxMap <MoguTokens>
	(__NONE__,"NONE")
	(self,"self")
	(parent,"parent")
	(children,"children")
	(children,"child")
	(siblings,"siblings")
	(siblings,"sibling")
	(application,"application")
	(application,"app")
	(change,"change")
	(add,"add")
	(subtract,"subtract")
	(subtract,"remove")
	(multiply,"multiply")
	(divide,"divide")
	(clear,"clear")
	(increment,"increment")
	(increment,"incr")
	(decrement,"decrement")
	(decrement,"decr")
	(test,"test")
	(test,"match")
	(email,"email")
	(reload,"reload")
	(reload,"refresh")
	(append,"append")
	(replace,"replace")
	(slide,"slide")
	(pop,"pop")
	(fade,"fade")
	(emit,"emit")
	(count,"count")
	(right,"right")
	(left,"left")
	(up,"up")
	(down,"down")
	(regex,"regex")
	(list,"list")
	(string,"string")
	(hash,"hash")
	(style,"style")
	(index,"index")
	(session,"session")
	(user,"user")
	(slot,"slot")
	(javascript,"javascript")
	(value,"value")
	(link,"link")
	(image,"image")
	(submit,"submit")
	(radio,"radio")
	(textarea,"textarea")
	(input,"input")
	(dropdown,"dropdown")
	(checkbox,"checkbox")
	(multi,"multi")
	(container,"container")
	(password,"password")
	(stack,"stack")
	(stack,"stacked")
	(foreach,"foreach")
	(index,"index")
	(name,"name")
	(hidden,"hidden")
	(value,"value")
;
