#include <declarations.h>

enum MoguToken {
	NONE
	,self
	,parent
	,children
	,siblings
	,application
	,change
	,add
	,subtract
	,multiply
	,divide
	,remove
	,clear
	,increment
	,decrement
	,match
	,email
	,reload
	,append
	,replace
	,slide
	,pop
	,fade
	,emit
	,count
	,right
	,left
	,up
	,down
	,regex
	,list
	,string
	,hash
	,style
	,index
	,session
	,user
	,slot
	,javascript
	,value
	,link
	,image
	,submit
	,radio
	,textarea
	,input
	,dropdown
	,checkbox
	,multi
	,container
	,password
	,stack
	,foreach
	,index
	,name
	,hidden
	,value
};


static std::map<std::string,MoguToken> tokenParser = create_map <std::string, MoguToken> ()
	("NONE")(NONE)
	("self")(self)
	("parent")(parent)
	("children")(children)
	("siblings")(siblings)
	("application")(application)
	("change")(change)
	("add")(add)
	("subtract")(subtract)
	("multiply")(multiply)
	("divide")(divide)
	("remove")(remove)
	("clear")(clear)
	("increment")(increment)
	("decrement")(decrement)
	("match")(match)
	("email")(email)
	("reload")(reload)
	("append")(append)
	("replace")(replace)
	("slide")(slide)
	("pop")(pop)
	("fade")(fade)
	("emit")(emit)
	("count")(count)
	("right")(right)
	("left")(left)
	("up")(up)
	("down")(down)
	("regex")(regex)
	("list")(list)
	("string")(string)
	("hash")(hash)
	("style")(style)
	("index")(index)
	("session")(session)
	("user")(user)
	("slot")(slot)
	("javascript")(javascript)
	("value")(value)
	("link")(link)
	("image")(image)
	("submit")(submit)
	("radio")(radio)
	("textarea")(textarea)
	("input")(input)
	("dropdown")(dropdown)
	("checkbox")(checkbox)
	("multi")(multi)
	("container")(container)
	("password")(password)
	("stack")(stack)
	("foreach")(foreach)
	("index")(index)
	("name")(name)
	("hidden")(hidden)
	("value")(value)
;
static std::map<MoguToken, std::string> reverseTokenParser = create_map <MoguToken,std::string> ()
	(NONE)("NONE")
	(self)("self")
	(parent)("parent")
	(children)("children")
	(siblings)("siblings")
	(application)("application")
	(change)("change")
	(add)("add")
	(subtract)("subtract")
	(multiply)("multiply")
	(divide)("divide")
	(remove)("remove")
	(clear)("clear")
	(increment)("increment")
	(decrement)("decrement")
	(match)("match")
	(email)("email")
	(reload)("reload")
	(append)("append")
	(replace)("replace")
	(slide)("slide")
	(pop)("pop")
	(fade)("fade")
	(emit)("emit")
	(count)("count")
	(right)("right")
	(left)("left")
	(up)("up")
	(down)("down")
	(regex)("regex")
	(list)("list")
	(string)("string")
	(hash)("hash")
	(style)("style")
	(index)("index")
	(session)("session")
	(user)("user")
	(slot)("slot")
	(javascript)("javascript")
	(value)("value")
	(link)("link")
	(image)("image")
	(submit)("submit")
	(radio)("radio")
	(textarea)("textarea")
	(input)("input")
	(dropdown)("dropdown")
	(checkbox)("checkbox")
	(multi)("multi")
	(container)("container")
	(password)("password")
	(stack)("stack")
	(foreach)("foreach")
	(index)("index")
	(name)("name")
	(hidden)("hidden")
	(value)("value")
;
