MoguSyntax = {
	"None"                           : (0,"null bit"),
	"own"                              : (1,"object"),
	"parent"                           : (2,"object"),
	"children"                         : (3,"object"),
	"siblings"                         : (4,"object"),
	"clicked"                   : (5,"event trigger"),
	"click"                     : (5,"event trigger"),
	"mouseover"                 : (6,"event trigger"),
	"style changed"             : (7,"event trigger"),
	"keyup"                     : (8,"event trigger"),
	"failed test"               : (9,"event trigger"),
	"succeeded test"           : (10,"event trigger"),
	"enter pressed"            : (11,"event trigger"),
	"hidden changed"           : (12,"event trigger"),
	"loaded"                   : (13,"event trigger"),
	"clear"                           : (14,"action"),
	"increment"                       : (15,"action"),
	"incr"                            : (15,"action"),
	"decrement"                       : (16,"action"),
	"decr"                            : (16,"action"),
	"test"                            : (17,"action"),
	"email"                           : (18,"action"),
	"reload"                          : (19,"action"),
	"append"                          : (20,"action"),
	"replace"                         : (21,"action"),
	"set"                    : (22,"action datatype"),
	"path"                            : (23,"object"),
	"user"                            : (24,"object"),
	"session"                         : (25,"object"),
	"reset"                           : (26,"action"),
	"style"                        : (27,"attribute"),
	"css"                          : (27,"attribute"),
	"group"                           : (28,"object"),
	"remove"                          : (29,"action"),
	"text"                         : (30,"attribute"),
	"content"                      : (30,"attribute"),
	"store"                           : (31,"action"),
	"child"                           : (32,"object"),
	"regex"                        : (33,"attribute"),
	"list"                : (34,"attribute datatype"),
	"string"              : (35,"attribute datatype"),
	"hash"                   : (36,"action datatype"),
	"index"                        : (37,"attribute"),
	"slot"                            : (38,"object"),
	"javascript"                      : (39,"action"),
	"link"                       : (40,"widget type"),
	"image"                      : (41,"widget type"),
	"submit"                     : (42,"widget type"),
	"radio"                      : (43,"widget type"),
	"textarea"                   : (44,"widget type"),
	"input"                      : (45,"widget type"),
	"dropdown"                   : (46,"widget type"),
	"multi"                      : (47,"widget type"),
	"container"                  : (48,"widget type"),
	"password"  : (49,"widget type attribute object"),
	"stack"                      : (50,"widget type"),
	"foreach"                    : (51,"widget type"),
	"name"                         : (52,"attribute"),
	"hidden"            : (53,"widget type attibute"),
	"image link"                 : (54,"widget type"),
	"to"                         : (55,"preposition"),
	"as"                         : (56,"preposition"),
} # END MoguSyntax

def as_integer(string):
    global MoguSyntax
    return MoguSyntax[string.strip()][0]
